server:
  port: 8080

spring:
  datasource:
    username: root
    password: songxiaoqi
    url: jdbc:mysql://106.13.101.219:3306/qm_db_prod?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.quming.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug